language: ruby
cache: bundler
bundler_args: --without development debug
sudo: required
rvm:
  - 2.1
before_install:
- export PATH="$PATH:$(pwd)/fits"
services:
- redis-server
before_script:
- redis-cli info
notifications:
email:
recipients:
- "peter.binkley@ualberta.ca"
on_success: "change"
on_failure: "always"
