development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://localhost:8983/fedora/rest
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://localhost:8983/fedora/rest
  base_path: /test
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://your.production.server:8080/fedora/rest
